"""create yield and bond tables

Revision ID: 89bed4304716
Revises: 
Create Date: 2026-04-05 12:53:07.463357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '89bed4304716'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bonds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isin', sa.String(length=12), nullable=False),
    sa.Column('coupon', sa.Float(), nullable=False),
    sa.Column('maturity', sa.Date(), nullable=False),
    sa.Column('face_value', sa.Float(), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=False),
    sa.Column('bond_type', sa.String(length=20), nullable=False),
    sa.Column('is_callable', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bonds_isin'), 'bonds', ['isin'], unique=True)
    op.create_table('fitted_curves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curve_date', sa.Date(), nullable=False),
    sa.Column('model', sa.String(length=30), nullable=False),
    sa.Column('params_json', sa.Text(), nullable=False),
    sa.Column('fitted_rates_json', sa.Text(), nullable=False),
    sa.Column('rmse', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fitted_curves_curve_date'), 'fitted_curves', ['curve_date'], unique=False)
    op.create_table('forward_curves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curve_date', sa.Date(), nullable=False),
    sa.Column('rates_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forward_curves_curve_date'), 'forward_curves', ['curve_date'], unique=True)
    op.create_table('par_yields',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curve_date', sa.Date(), nullable=False),
    sa.Column('yields_json', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_par_yields_curve_date'), 'par_yields', ['curve_date'], unique=True)
    op.create_table('pricing_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bond_isin', sa.String(length=12), nullable=False),
    sa.Column('curve_date', sa.Date(), nullable=False),
    sa.Column('clean_price', sa.Float(), nullable=False),
    sa.Column('dirty_price', sa.Float(), nullable=False),
    sa.Column('ytm', sa.Float(), nullable=False),
    sa.Column('z_spread', sa.Float(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('modified_duration', sa.Float(), nullable=False),
    sa.Column('convexity', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_results_bond_isin'), 'pricing_results', ['bond_isin'], unique=False)
    op.create_table('spot_curves',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('curve_date', sa.Date(), nullable=False),
    sa.Column('rates_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_spot_curves_curve_date'), 'spot_curves', ['curve_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_spot_curves_curve_date'), table_name='spot_curves')
    op.drop_table('spot_curves')
    op.drop_index(op.f('ix_pricing_results_bond_isin'), table_name='pricing_results')
    op.drop_table('pricing_results')
    op.drop_index(op.f('ix_par_yields_curve_date'), table_name='par_yields')
    op.drop_table('par_yields')
    op.drop_index(op.f('ix_forward_curves_curve_date'), table_name='forward_curves')
    op.drop_table('forward_curves')
    op.drop_index(op.f('ix_fitted_curves_curve_date'), table_name='fitted_curves')
    op.drop_table('fitted_curves')
    op.drop_index(op.f('ix_bonds_isin'), table_name='bonds')
    op.drop_table('bonds')
    # ### end Alembic commands ###
